### ISSUE TITLE
BUILD_CASCEXAMPLES cmake variable not recognized

### ISSUE THREAD

**Issue by AstroStucky** [ctlee/casc#11]
I would like to build your examples, so following the README, I run `$ cmake -DBUILD_CASCEXAMPLES=on ..` in the build directory and get
```
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- casc v1.0.5
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Doxygen Executable: /usr/bin/doxygen
-- Build the documentation using `make docs`
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_CASCEXAMPLES
```

Only the tests seem to get configured by cmake, and the variable mentioned in the readme doesn't seem to exist.

**Comment by ctlee** [comment]
Thanks for checking out CASC and for filing an issue! I'm reminded that the examples in this repo are incomplete. While I work on putting some things together for this I recommend checking out [GAMer](https://github.com/ctlee/gamer/) which uses CASC and is the basis for the reduced complexity examples in this repo.

The `SurfaceMesh` and `TetMesh` classes are of particular interest.

https://github.com/ctlee/gamer/blob/master/include/gamer/SurfaceMesh.h
https://github.com/ctlee/gamer/blob/master/src/SurfaceMesh.cpp

**Comment by AstroStucky** [comment]
Thanks! That's just as good. I'll be sure to check it out.
